#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

export REPO_ROOT
export AGENTMAIL_API_KEY_FILE="${AGENTMAIL_API_KEY_FILE:-$REPO_ROOT/secrets/agentmail-api-key.txt}"
export AGENTMAIL_CONFIG_FILE="${AGENTMAIL_CONFIG_FILE:-$REPO_ROOT/config/agentmail.env}"
export AGENTMAIL_BASE_URL="${AGENTMAIL_BASE_URL:-https://api.agentmail.to/v0}"
export AGENTMAIL_INBOX_ID="${AGENTMAIL_INBOX_ID:-}"

python3 - <<'PY'
import json
import os
import shlex
import sys
import urllib.error
import urllib.request
from pathlib import Path


SHARED_INBOX_CLIENT_ID = "personalagentkit-shared-inbox-v1"
SHARED_INBOX_DISPLAY_NAME = "PersonalAgentKit Shared Inbox"
SETUP_PATH = "hooks/setup-agentmail.sh"
FALLBACK_NOTE = "shared inbox by client_id; create failure falls back to first listed inbox"


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def request_json(url: str, api_key: str, *, method: str = "GET", payload: dict | None = None) -> dict:
    body = None
    if payload is not None:
        body = json.dumps(payload).encode()
    request = urllib.request.Request(
        url,
        data=body,
        method=method,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def list_inboxes(base_url: str, api_key: str) -> list[dict]:
    payload = request_json(f"{base_url}/inboxes", api_key)
    return payload.get("inboxes") or []


def choose_shared_inbox(inboxes: list[dict]) -> str:
    for inbox in inboxes:
        inbox_id = str(inbox.get("inbox_id") or "").strip()
        client_id = str(inbox.get("client_id") or "").strip()
        if inbox_id and client_id == SHARED_INBOX_CLIENT_ID:
            return inbox_id
    return ""


def choose_first_inbox(inboxes: list[dict]) -> str:
    for inbox in inboxes:
        inbox_id = str(inbox.get("inbox_id") or "").strip()
        if inbox_id:
            return inbox_id
    return ""


def persist_config(path: Path, inbox_id: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                f"# Generated by ./{SETUP_PATH}",
                f"export AGENTMAIL_INBOX_ID={shlex.quote(inbox_id)}",
                "",
            ]
        )
    )


config_file = Path(os.environ["AGENTMAIL_CONFIG_FILE"])
api_key_file = Path(os.environ["AGENTMAIL_API_KEY_FILE"])
base_url = os.environ["AGENTMAIL_BASE_URL"].rstrip("/")
explicit_inbox = os.environ.get("AGENTMAIL_INBOX_ID", "").strip()
existing_inbox = parse_env_file(config_file).get("AGENTMAIL_INBOX_ID", "").strip()

if explicit_inbox:
    print(
        f"fetch-agentmail: setup via {SETUP_PATH} skipped; AGENTMAIL_INBOX_ID already set "
        f"({FALLBACK_NOTE})"
    )
    sys.exit(0)

if existing_inbox:
    print(
        f"fetch-agentmail: setup via {SETUP_PATH} reused config/agentmail.env "
        f"({FALLBACK_NOTE})"
    )
    sys.exit(0)

if not api_key_file.exists():
    print(f"fetch-agentmail: missing API key file: {api_key_file}", file=sys.stderr)
    sys.exit(0)

api_key = api_key_file.read_text().strip()
if not api_key:
    print(f"fetch-agentmail: API key file is empty: {api_key_file}", file=sys.stderr)
    sys.exit(0)

listed_inboxes: list[dict] = []
listing_error: Exception | None = None
try:
    listed_inboxes = list_inboxes(base_url, api_key)
except Exception as exc:
    listing_error = exc

shared_inbox = choose_shared_inbox(listed_inboxes)
if shared_inbox:
    persist_config(config_file, shared_inbox)
    print(
        f"fetch-agentmail: setup via {SETUP_PATH} ready "
        f"(source=shared-inbox:list-client-id; {FALLBACK_NOTE})"
    )
    sys.exit(0)

try:
    created = request_json(
        f"{base_url}/inboxes",
        api_key,
        method="POST",
        payload={
            "client_id": SHARED_INBOX_CLIENT_ID,
            "display_name": SHARED_INBOX_DISPLAY_NAME,
        },
    )
    created_inbox = str(created.get("inbox_id") or "").strip()
    if created_inbox:
        persist_config(config_file, created_inbox)
        print(
            f"fetch-agentmail: setup via {SETUP_PATH} ready "
            f"(source=shared-inbox:create-client-id; {FALLBACK_NOTE})"
        )
        sys.exit(0)
    print("fetch-agentmail: shared Agentmail inbox create returned no inbox_id", file=sys.stderr)
except Exception:
    pass

fallback_inbox = choose_first_inbox(listed_inboxes)
if not fallback_inbox:
    try:
        fallback_inbox = choose_first_inbox(list_inboxes(base_url, api_key))
    except Exception as exc:
        if listing_error is None:
            listing_error = exc

if fallback_inbox:
    persist_config(config_file, fallback_inbox)
    print(
        f"fetch-agentmail: setup via {SETUP_PATH} ready "
        f"(source=fallback:list-first; {FALLBACK_NOTE})"
    )
    sys.exit(0)

print(
    "fetch-agentmail: no usable Agentmail inbox; set "
    "'export AGENTMAIL_INBOX_ID=<id>' in config/agentmail.env to enable this optional hook",
    file=sys.stderr,
)
if listing_error is not None:
    print(f"fetch-agentmail: inbox discovery also failed: {listing_error}", file=sys.stderr)
sys.exit(0)
PY
